#!/bin/bash

set -e # exit on error


#####################################################################################
# Default variables (search this file for "Post-processing defaults" to see others)
#####################################################################################
time="3days"

#####################################################################################
# Usage
#####################################################################################
print_usage()
{
    # Display Help
    echo "SLURM sacct wrapper. Prints the information I find most useful, with"
    echo "  convenience wrappers for arguments I use most frequently."
    echo
    echo "Brief syntax:"
    echo "${0##*/} [OPTIONS(0)...] [ : [OPTIONS(N)...]] -- <cmd>"
    echo
    echo "Full syntax:"
    echo "${0##*/} [-h|--help] [-t|--time] [-u|--units]"
    echo
    echo "options without args:"
    echo "-h, --help                : Print this help."
    echo
    echo "-t, --time <val>          : Time frame to report results. Default: 3days."
    echo
}

#####################################################################################
# Parse input arguments
#####################################################################################
while [[ $# -gt 0 ]]
do
    key="$1"
    shift
    case $key in
        -h|--help)
            print_usage
            exit 0
        ;;
        -t|--time)
            time=$1
            shift
        ;;
        *)
            echo -e "\n\nUnknown argument: $key\n\n"
            print_usage
            exit 1
        ;;
    esac
done

echo -n "Printing jobs over last $time. "

export SLURM_TIME_FORMAT="%d/%m %H:%M:%S"
sacct -S now-"${time}" -E now $state -X --format="jobid,jobname%40,partition,elapsed,timelimit,state,submit,start"
