#!/bin/bash

set -e # exit on error

# cleanup -- delete temporary file
function cleanup {
    rm -f "${tmp_file}"
}
trap cleanup EXIT

#####################################################################################
# Default variables (search this file for "Post-processing defaults" to see others)
#####################################################################################
run_dir=$(pwd)
gpu=1
cpu=10
exp="${JADE_EXPORT}"
out="${HOME}/job_logs/%j.out"
partition=small
nodes=1
default_devel_time_limit="1"
default_time_limit="6"
check=True
follow=True
cmd="sleep infinity"
jupyter=False
vscode_server=False
conda_env="${JADE_CONDA}"

#####################################################################################
# Usage
#####################################################################################
print_usage()
{
    echo "SLURM submit script for JADE. Anything after the double hyphen will be executed as command in job."
    echo "  This could be \"python script.py\", for example."
    echo
    echo "Brief syntax:"
    echo "${0##*/} [OPTIONS(0)...] [ : [OPTIONS(N)...]] -- <cmd>"
    echo
    echo "Full syntax:"
    echo "${0##*/} [-h|--help] [-m|--mail] [-f|--follow <val>]"
    echo "                  [-d|--dir <val>] [-t|--time <val>]"
    echo "                  [-g|--gpu <val>] [-n,--cpu <val>]"
    echo "                  [-J|--name <val>] [-e|--exp <val>]"
    echo "                  [-o|--out <val>] [-p|--partition <val>]"
    echo "                  [-N|--nodes <val>] [-C|--check <val>]"
    echo "                  [-v|--vscode <val>] [-j|--jupyter <val>]"
    echo "                  [-c|--conda <val>] -- <cmd>"
    echo
    echo "options without args:"
    echo "-h, --help                : Print this help."
    echo "-m, --mail                : Send status emails. Will read email address from environment"
    echo "                             variable \`JADE_EMAIL\`. If missing, an error will be raised."
    echo
    echo "options with args:"
    echo "-d, --dir <val>           : Directory to run from. Default: \`pwd\`."
    echo "-t, --time <val>          : Time limit. Default: ${default_devel_time_limit}h if partition is devel, else ${default_time_limit}h."
    echo "-g, --gpu <val>           : Num GPUs. Default: ${gpu}."
    echo "-n, --cpu <val>           : Num CPUs. Default: ${cpu}."
    echo "-J, --name <val>          : Job name. Default: \`<cmd>\` (with \`python \` stripped if present)."
    echo "-e, --exp <val>           : Environment variables to export (comma separated)."
    echo "                             Default read from environment variable \`JADE_EXPORT\`."
    echo "                             If this environment variable is not present, nothing is exported."
    echo "-f, --follow <val>        : After submitting, follow job. Default: ${follow}."
    echo "-o, --out <val>           : File to save output. Default: \`$HOME/job_logs/%j.out\`."
    echo "                             %j is jobid. Folder will be created if necessary."
    echo "-p, --partition <val>     : Partition to use. Default: ${partition}."
    echo "-N, --nodes <val>         : Number of nodes. Default: ${nodes}."
    echo "-C, --check <val>         : If true, and cmd is given, get filename and check it exists."
    echo "                             deleted? Default: ${check}."
    echo "-j, --jupyter <val>       : If true, start an instance of \`jupyter notebook\`. A randomly selected free port"
    echo "                             will be used, and this port will be printed to the jobs log along with the"
    echo "                             compute hostname. You can then create a tunnel connection"
    echo "                             from your local through the JADE login node and finishing with the compute"
    echo "                             node, e.g.,: ssh -L <port>:<hostname>:<port> jade. Default: ${jupyter}"
    echo "-v, --vscode <val>        : If true, start an instance of \`vscode-server\`. A randomly selected free port"
    echo "                             will be used, and this port will be printed to the jobs log along with the"
    echo "                             server token and compute hostname. You can then create a tunnel connection"
    echo "                             from your local through the JADE login node and finishing with the compute"
    echo "                             node, e.g.,: ssh -L <port>:<hostname>:<port> jade. Default: ${vscode_server}"
    echo "-c, --conda <val>         : Conda environment to use. If not given, use the \`JADE_CONDA\` env variable."
    echo "                             If \`JADE_CONDA\` does not exist, do not activate a conda environment."
    echo
}

#####################################################################################
# Parse input arguments
#####################################################################################
while [[ $# -gt 0 ]]; do
    key="$1"
    shift
    if [ "$key" == "--" ]; then
        if [ "$#" -gt 0 ]; then
            cmd="$*"
        fi
        break
    fi
    case $key in
        -h|--help)
            print_usage
            exit 0
        ;;
        -d|--dir)
            run_dir=$1
            shift
        ;;
        -t|--time)
            time_limit=$1
            shift
        ;;
        -g|--gpu)
            gpu=$1
            shift
        ;;
        -n|--cpu)
            cpu=$1
            shift
        ;;
        -J|--name)
            job_name=$1
            shift
        ;;
        -m|--mail)
            use_mail=true
        ;;
        -f|--follow)
            follow="$1"
            shift
        ;;
        -e|--exp)
            exp="${1}"
            shift
        ;;
        -o|--out)
            out=$1
            shift
        ;;
        -p|--partition)
            partition=$1
            shift
        ;;
        -N|--nodes)
            nodes=$1
            shift
        ;;
        -C|--check)
            check=$1
            shift
        ;;
        -j|--jupyter)
            jupyter=$1
            shift
        ;;
        -v|--vscode_server)
            vscode_server=$1
            shift
        ;;
        -c|--conda)
            conda_env=$1
            shift
        ;;
        *)
            echo -e "\n\nUnknown argument: $key\n\n"
            print_usage
            exit 1
        ;;
    esac
done

#####################################################################################
# Post-process input arguments
#####################################################################################

# default time limit
if [ "${time_limit}" == "" ]; then
    if [ "$partition" == "devel" ]; then
        time_limit="0${default_devel_time_limit}:00:00"
    else
        time_limit="0${default_time_limit}:00:00"
    fi
fi

log_fname=${out/\%j/${job_id}}
# default job name is cmd, with certain parts stripped.
default_job_name=$cmd
default_job_name=$(echo $default_job_name | sed -E -e 's/.*python//')
default_job_name=$(echo $default_job_name | sed -E -e 's/\.py//')
: ${job_name:=\"$default_job_name\"}

# If email desired
if [ "$use_mail" = true ]; then
    email_to_use="${JADE_EMAIL}"
    if [ -z "${email_to_use}" ]; then
        echo "Set JADE_EMAIL to use the --mail argument."
        exit 1
    fi
    mail="#SBATCH --mail-type=INVALID_DEPEND,END,FAIL,REQUEUE,STAGE_OUT\n#SBATCH --mail-user=${email_to_use}"
fi

# If environment variables to be exported
if [ "${exp}" != "" ]; then
    exp_cmd="#SBATCH --export=${exp}"
fi

# Make sure output folder exists
mkdir -p "$(dirname "$out")"

# Print vals
echo
echo "Nodes: ${nodes}"
echo "Time limit: ${time_limit}"
echo "Num GPUs: ${gpu}"
echo "Num CPUs: ${cpu}"
echo "Job name: ${job_name}"
echo "Log file: ${out}"
echo "Partition: ${partition}"
echo "Exports: ${exp}"
echo "Email: ${email_to_use:-No}"
echo "Check?: ${check}"
echo "Follow?: ${follow}"
echo "Jupyter notebook?: ${jupyter}"
echo "VSCode server?: ${vscode_server}"
echo "Conda env: ${conda_env}"
echo
echo "Path: ${run_dir}"
echo "Command: ${cmd}"
echo

#####################################################################################
# Check file exists in command
#####################################################################################
if [ "${check}" == True ]; then
    # loop over each word in cmd
    for i in ${cmd}; do
        # if one contains .py, check file exists
        if [[ $i == *".py" ]]; then
            path="${run_dir}/$i"
            if [ ! -f "$path" ]; then
                echo "$path: does not exist. Use --check False if this is expected."
                exit 1
            fi
            break
        fi
    done
fi

#####################################################################################
# Create temporary submit file
#####################################################################################

# Create submit file (temp, deleted by cleanup function)
tmp_file=/tmp/tmp_submit_${RANDOM}.sh
cat > ${tmp_file} << EOL
#!/bin/bash

#SBATCH --nodes=${nodes}
#SBATCH -J ${job_name}
#SBATCH --gres=gpu:${gpu}
#SBATCH --time=${time_limit}
#SBATCH -p ${partition}
#SBATCH --chdir ${run_dir}
#SBATCH -n ${cpu}
${exp_cmd}
$(echo -e "${mail}")
#SBATCH --out ${out}

set -e # exit on error

echo hostname: \$(hostname)

# conda env if given
if [ "${conda_env}" != "" ]; then
    echo -e "\nactivating conda environment ${conda_env}..."
    source $CONDA_PREFIX/etc/profile.d/conda.sh
    conda activate ${conda_env}
fi

function cleanup {
    rm -f \${jupy_file} \${vs_file}
}
trap cleanup EXIT

if [ "$vscode_server" == True ]; then
    echo -e "\nstarting vscode-server..."
    module load use.dev
    module load code-server &> /dev/null
    vs_file=/tmp/nohup_vscode_${RANDOM}.out
    code-server --accept-server-license-terms --disable-telemetry  \
        --host 0.0.0.0 --port 8866-8887 serve-local > \$vs_file 2>&1 &
    sleep 10
    echo vscode-server URL: \$(grep -oP '(http://.*)$' \${vs_file})
fi

if [ "$jupyter" == True ]; then
    echo -e "\nstarting jupyter notebook..."
    jupy_file=/tmp/nohup_jupyter_${RANDOM}.out
    nohup jupyter notebook --ip 0.0.0.0 --no-browser --notebook-dir="~" > \$jupy_file 2>&1 &
    sleep 60
    echo Jupyter URL: \$(grep -oP '(http://.*)$' \${jupy_file})
fi

# the trap code is designed to send a stop (SIGTERM) signal to child processes,
# thus allowing python code to catch the signal and execute a callback
trap 'trap " " SIGTERM; kill 0; wait' SIGTERM

echo -e "\nrunning ${cmd}"

${cmd} &
wait \$!
EOL

#####################################################################################
# Submit and print info
#####################################################################################

# Submit
sbatch_out=$(sbatch ${tmp_file})
sbatch_success=$?
# If successful, print job info
if [ "$sbatch_success" -eq 0 ]; then
    job_id=$(echo "$sbatch_out" | awk '{print $NF}')
    # print info about job
    scontrol show job "${job_id}"
fi
# Always print sbatch output
echo "${sbatch_out}"

# If successful and following desired
if [ "$sbatch_success" -eq 0 ] && [ "$follow" == True ]; then
    echo "Waiting for job to start..."
    log_fname=${out/\%j/${job_id}}
    while [ ! -f "$log_fname" ]; do
        sleep 1
    done
    tail -f "$log_fname"
fi
