[tool.black]
line-length = 120
skip-string-normalization = true
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | build
  | dist
)/
'''

[tool.isort]
profile = "black"
line_length = 120
use_parentheses = true
include_trailing_comma = true
multi_line_output = 3
known_first_party = ["pipeline", "enactsdk"]
known_local_folder = ["template"]

[tool.ruff]
exclude = [
    ".git",
    ".idea",
    ".vscode",
    "__pycache__",
    ".pytest_cache",
    ".ipynb_checkpoints",
    "build",
    "dist",
    "data",
    "*/*.jpg",
    "*/*.png",
]
ignore = ["E401"]
line-length = 120
select = [
  # "D", # pydocstyle - uncomment if you want to use
  "E", # pycodestyle
  "F", # pyFlakes
  "I", # isort
  "N", # pep8-naming
  "W", # Warning
]

fixable = ["E", "F", "I", "N", "W"]

[tool.ruff.per-file-ignores]
"__init__.py" = ["F401"]
