#!/bin/sh

use_ubuntu=$use_ubuntu

if [ \$use_ubuntu = true ]; then
    export XKL_XMODMAP_DISABLE=1
    unset SESSION_MANAGER
    unset DBUS_SESSION_BUS_ADDRESS
fi

[ -x /etc/vnc/xstartup ] && exec /etc/vnc/xstartup
[ -r $HOME/.Xresources ] && xrdb $HOME/.Xresources

xsetroot -solid grey

if [ \$use_ubuntu = true ]; then
    vncconfig -iconic &
    gnome-panel &
    gnome-settings-daemon &
    metacity &
    nautilus &
    gnome-terminal &
else
    x-window-manager &
    xfce4-session &
fi
