#!/bin/bash

set -e # exit on error

#####################################################################################
# Usage
#####################################################################################
print_usage()
{
    # Display Help
    echo "SLURM squeue wrapper sorted by JOBID. Prints the information I find most useful. "
    echo "All arguments to this script are passed to squeue."
    echo
    echo "Syntax:"
    echo "${0##*/} [-h|--help] [squeue_options]"
    echo
    echo "options without args:"
    echo "-h, --help                : Print this help."
    echo
}

#####################################################################################
# Parse input arguments
#####################################################################################
if [[ $# -gt 0 ]]; then
    key="$1"
    case $key in
        -h|--help)
            print_usage
            exit 0
        ;;
        *)
            args="$@"
        ;;
    esac
fi

echo -e "Number of jobs running: $(squeue --me | tail +2 | wc -l)\n"

export SLURM_TIME_FORMAT="%d/%m %H:%M:%S"
export SQUEUE_FORMAT='%.5i|||%u|||%.9P|||%60j|||%40R|||%8T|||%20V|||%20S|||%10M|||%15l|||%6D|||%20b|||%31r'

squeue -S i $args | sed -r 's/  +//g' | column -t -s '|||'
